"""Bounded subprocess runner for Python generated by the pseudocode compiler.

This is deliberately separate from the compiler and HTTP layers.  Generated
code is never ``exec``-uted in the long-lived IDE server process: a fresh,
isolated-mode Python child owns the program's stdin, stdout and stderr.

This is process containment, not a general-purpose hostile-code sandbox.
``-I`` removes the repository and user site-packages from Python's import
environment, while the timeout and byte budgets bound the resources exposed by
the IDE.  The compiler remains the authority over what Python can be emitted.
"""

from __future__ import annotations

import os
import json
from pathlib import Path
import signal
import subprocess
import sys
import tempfile
import time


DEFAULT_TIMEOUT_SECONDS = 3.0
MAX_STDIN_BYTES = 64 * 1024
MAX_OUTPUT_BYTES = 64 * 1024


# The wrapper runs under ``python -I -u``.  It shares one UTF-8 byte budget
# between stdout and stderr so a noisy program cannot evade the output limit by
# alternating streams.  Marker files communicate truncation without adding a
# protocol message to the student's output.
_CHILD_WRAPPER = r'''
import json
import pathlib
import sys
import traceback

program_path = pathlib.Path(sys.argv[1])
marker_directory = pathlib.Path(sys.argv[2])
limit = int(sys.argv[3])
entrypoint_path = pathlib.Path(sys.argv[4])
workspace_root = (
    pathlib.Path(sys.argv[5]).resolve()
    if len(sys.argv) > 5 and sys.argv[5]
    else None
)
_real_open = open

for stream in (sys.stdin, sys.stdout, sys.stderr):
    try:
        stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass


class _Budget:
    def __init__(self, size):
        self.remaining = size


class _LimitedTextWriter:
    def __init__(self, wrapped, budget, marker_name):
        self._wrapped = wrapped
        self._budget = budget
        self._marker = marker_directory / marker_name
        self._marked = False
        self.encoding = "utf-8"
        self.errors = "replace"

    def _mark_truncated(self):
        if self._marked:
            return
        self._marked = True
        try:
            self._marker.touch(exist_ok=True)
        except OSError:
            pass

    def write(self, value):
        if not isinstance(value, str):
            value = str(value)
        encoded = value.encode("utf-8", errors="replace")
        if len(encoded) <= self._budget.remaining:
            self._wrapped.write(value)
            self._budget.remaining -= len(encoded)
            return len(value)

        allowed = max(0, self._budget.remaining)
        prefix = encoded[:allowed].decode("utf-8", errors="ignore")
        if prefix:
            self._wrapped.write(prefix)
        self._budget.remaining = 0
        self._mark_truncated()
        return len(value)

    def flush(self):
        self._wrapped.flush()

    def isatty(self):
        return False

    def writable(self):
        return True


budget = _Budget(limit)
sys.stdout = _LimitedTextWriter(sys.stdout, budget, "stdout.truncated")
sys.stderr = _LimitedTextWriter(sys.stderr, budget, "stderr.truncated")


_real_import = __import__


class _RandomProxy:
    """Expose only the one operation emitted for the pseudocode RAND builtin."""

    @staticmethod
    def random():
        return _real_import("random").random()


_random_proxy = _RandomProxy()


def _allowed_import(name, globals=None, locals=None, fromlist=(), level=0):
    if level:
        raise ImportError("generated programs may only import 'random' or 'json'")
    if name == "random":
        # Returning the real module would also expose implementation details such
        # as random._os.  The generated RAND expression needs only `.random()`.
        return _random_proxy
    if name == "json":
        return _real_import("json")
    raise ImportError("generated programs may only import 'random' or 'json'")


def _sandboxed_open(file, mode="r", buffering=-1, encoding=None, errors=None,
                    newline=None, closefd=True, opener=None):
    if workspace_root is None:
        raise NameError("open")
    raw = str(file)
    name = pathlib.Path(raw).name
    if not name or name in {".", ".."}:
        raise OSError("file access is limited to the workspace folder")
    target = (workspace_root / name).resolve()
    if workspace_root not in target.parents and target != workspace_root:
        raise OSError("file access is limited to the workspace folder")
    if target == workspace_root:
        raise OSError("file access is limited to the workspace folder")
    text_mode = "b" not in str(mode)
    open_kwargs = {"buffering": buffering, "errors": errors, "closefd": closefd}
    if opener is not None:
        open_kwargs["opener"] = opener
    if text_mode:
        open_kwargs["encoding"] = "utf-8" if encoding is None else encoding
        open_kwargs["newline"] = "" if newline is None else newline
    else:
        if encoding is not None:
            open_kwargs["encoding"] = encoding
        if newline is not None:
            open_kwargs["newline"] = newline
    return _real_open(target, mode, **open_kwargs)


safe_builtins = {
    "__build_class__": __build_class__,
    "__import__": _allowed_import,
    "abs": abs,
    "all": all,
    "any": any,
    "bool": bool,
    "chr": chr,
    "dict": dict,
    "enumerate": enumerate,
    "float": float,
    "input": input,
    "int": int,
    "len": len,
    "list": list,
    "max": max,
    "min": min,
    "object": object,
    "ord": ord,
    "pow": pow,
    "print": print,
    "range": range,
    "round": round,
    "set": set,
    "str": str,
    "sum": sum,
    "super": super,
    "tuple": tuple,
    "zip": zip,
    "hasattr": hasattr,
    "getattr": getattr,
    "setattr": setattr,
    "isinstance": isinstance,
    "Exception": Exception,
    "TypeError": TypeError,
    "ValueError": ValueError,
    "OSError": OSError,
    "FileNotFoundError": FileNotFoundError,
    "RuntimeError": RuntimeError,
    "KeyError": KeyError,
    "IndexError": IndexError,
    "AttributeError": AttributeError,
}
if workspace_root is not None:
    safe_builtins["open"] = _sandboxed_open


def _convert_parameter(raw, type_name):
    stripped = raw.strip()
    if type_name == "INTEGER":
        return int(stripped)
    if type_name == "REAL":
        return float(stripped)
    if type_name == "BOOLEAN":
        return stripped.upper() == "TRUE"
    if type_name == "CHAR":
        return stripped[0] if stripped else ""
    return raw.rstrip("\r\n")


def _invoke_entrypoint(namespace, metadata):
    if not metadata:
        return
    name = metadata["name"]
    function = namespace.get(name)
    if not callable(function):
        raise RuntimeError("compiled entrypoint is not callable: " + name)
    arguments = []
    display_arguments = []
    for parameter in metadata.get("parameters", []):
        raw = sys.stdin.readline()
        if raw == "":
            raise EOFError(
                "missing stdin line for parameter '" + parameter["name"] + "'"
            )
        value = _convert_parameter(raw, parameter.get("type", "STRING"))
        display_arguments.append(value)
        if parameter.get("passBy") == "BYREF":
            value = [value]
        arguments.append(value)
    result = function(*arguments)
    if metadata.get("kind") == "function" and result is not None:
        rendered = ", ".join(repr(value) for value in display_arguments)
        print(f">>> {name}({rendered}) = {result!r}")


exit_code = 0
try:
    generated = program_path.read_text(encoding="utf-8")
    metadata = json.loads(entrypoint_path.read_text(encoding="utf-8"))
    compiled = compile(generated, "<generated-pseudocode>", "exec")
    namespace = {
        "__builtins__": safe_builtins,
        "__name__": "__main__",
        "__file__": "<generated-pseudocode>",
    }
    exec(compiled, namespace, namespace)
    _invoke_entrypoint(namespace, metadata)
except SystemExit as exc:
    if exc.code is None:
        exit_code = 0
    elif isinstance(exc.code, int):
        exit_code = exc.code
    else:
        print(exc.code, file=sys.stderr)
        exit_code = 1
except BaseException:
    traceback.print_exc()
    exit_code = 1
finally:
    try:
        sys.stdout.flush()
        sys.stderr.flush()
    except Exception:
        pass

raise SystemExit(exit_code)
'''


def execute_python(
    python_code: str,
    stdin: str = "",
    *,
    entrypoint: dict | None = None,
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS,
    max_stdin_bytes: int = MAX_STDIN_BYTES,
    max_output_bytes: int = MAX_OUTPUT_BYTES,
    workspace: Path | None = None,
) -> dict:
    """Execute generated Python in a bounded child process.

    The returned dictionary is JSON-ready.  ``exitCode`` is ``None`` when the
    process exceeded its deadline because the forced-termination status is not
    a meaningful program exit code.
    """
    if not isinstance(python_code, str):
        raise ValueError("generated Python must be a string")
    if not isinstance(stdin, str):
        raise ValueError("stdin must be a string")
    stdin_bytes = stdin.encode("utf-8")
    if len(stdin_bytes) > max_stdin_bytes:
        raise ValueError(
            f"stdin is too large (maximum {max_stdin_bytes} UTF-8 bytes)"
        )
    if timeout_seconds <= 0:
        raise ValueError("timeout must be positive")
    if max_output_bytes <= 0:
        raise ValueError("output limit must be positive")

    started = time.perf_counter()
    timed_out = False

    with tempfile.TemporaryDirectory(prefix="pseudocode-ide-") as directory:
        workdir = Path(directory)
        program_path = workdir / "generated.py"
        program_path.write_text(python_code, encoding="utf-8", newline="\n")
        entrypoint_path = workdir / "entrypoint.json"
        entrypoint_path.write_text(
            json.dumps(entrypoint, ensure_ascii=True),
            encoding="utf-8",
            newline="\n",
        )

        command = [
            sys.executable,
            "-I",
            "-u",
            "-c",
            _CHILD_WRAPPER,
            str(program_path),
            str(workdir),
            str(max_output_bytes),
            str(entrypoint_path),
            str(workspace.resolve()) if workspace is not None else "",
        ]
        popen_options = _process_group_options()
        child_cwd = Path(workspace).resolve() if workspace is not None else workdir
        process = subprocess.Popen(
            command,
            cwd=str(child_cwd),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=_isolated_environment(),
            **popen_options,
        )
        try:
            stdout_bytes, stderr_bytes = process.communicate(
                input=stdin_bytes,
                timeout=timeout_seconds,
            )
        except subprocess.TimeoutExpired:
            timed_out = True
            _terminate_process_tree(process)
            try:
                stdout_bytes, stderr_bytes = process.communicate(timeout=1.0)
            except subprocess.TimeoutExpired:
                process.kill()
                stdout_bytes, stderr_bytes = process.communicate()

        marker_truncated = (
            (workdir / "stdout.truncated").exists()
            or (workdir / "stderr.truncated").exists()
        )

    # The child wrapper is the first line of defence.  Cap again in the parent
    # in case generated code ever gains access to binary stream/file-descriptor
    # writes that bypass the text wrappers.
    stdout_bytes, stderr_bytes, parent_truncated = _cap_combined_output(
        stdout_bytes,
        stderr_bytes,
        max_output_bytes,
    )
    return {
        "stdout": stdout_bytes.decode("utf-8", errors="replace"),
        "stderr": stderr_bytes.decode("utf-8", errors="replace"),
        "exitCode": None if timed_out else process.returncode,
        "timedOut": timed_out,
        "truncated": marker_truncated or parent_truncated,
        "elapsedMs": round((time.perf_counter() - started) * 1000, 2),
    }


def _isolated_environment() -> dict[str, str]:
    """Keep OS essentials without copying secrets into the child process."""
    allowed_keys = {
        "SYSTEMROOT", "WINDIR", "TEMP", "TMP",  # Windows runtime/temp
        "TMPDIR", "LANG", "LC_ALL",             # POSIX runtime/temp
    }
    environment = {
        key: value
        for key, value in os.environ.items()
        if key.upper() in allowed_keys
    }
    return environment


def _process_group_options() -> dict:
    if os.name == "nt":
        return {
            "creationflags": (
                subprocess.CREATE_NEW_PROCESS_GROUP
                | getattr(subprocess, "CREATE_NO_WINDOW", 0)
            )
        }
    return {"start_new_session": True}


def _terminate_process_tree(process: subprocess.Popen) -> None:
    """Forcefully terminate the child and any descendants it created."""
    if process.poll() is not None:
        return
    if os.name == "nt":
        system_root = os.environ.get("SystemRoot", r"C:\Windows")
        taskkill = Path(system_root) / "System32" / "taskkill.exe"
        try:
            subprocess.run(
                [str(taskkill), "/PID", str(process.pid), "/T", "/F"],
                stdin=subprocess.DEVNULL,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=1.0,
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
                check=False,
            )
        except (OSError, subprocess.SubprocessError):
            process.kill()
    else:
        try:
            os.killpg(process.pid, signal.SIGKILL)
        except (OSError, ProcessLookupError):
            process.kill()


def _cap_combined_output(
    stdout: bytes,
    stderr: bytes,
    limit: int,
) -> tuple[bytes, bytes, bool]:
    original_size = len(stdout) + len(stderr)
    stdout = stdout[:limit]
    remaining = max(0, limit - len(stdout))
    stderr = stderr[:remaining]
    return stdout, stderr, original_size > limit
